name: Test
on:
  pull_request: {}
  push: 
    branches:
    - master
    - ci/*

jobs:
  cargo_test:
    name: Cargo Test
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Rust nightly-2021-05-18
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2021-05-18
            override: true
      - uses: Swatinem/rust-cache@v1

      - run: |
          cargo test --lib
          cargo test -p citeproc-io --test integration

  regressions:
    name: CSL Test Suite Regressions
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract branch name
        id: branch
        shell: bash
        run: |
          IS_CI_TEST=${{ github.event_name == 'push' && github.ref != 'refs/heads/master' && 'true' || 'false '}}
          GITHUB_HEAD=${{ github.head_ref }}
          GITHUB_BASE=${{ github.base_ref }}

          if test -z "$GITHUB_HEAD"; then
            GITHUB_HEAD="$GITHUB_REF"
          fi
          if test -z "$GITHUB_BASE"; then
            GITHUB_BASE="$GITHUB_REF"
          fi

          # transforms refs/pulls/123/merge into pulls-123-merge
          GITHUB_HEAD=${GITHUB_HEAD#refs/heads/}
          GITHUB_HEAD=$(echo ${GITHUB_HEAD#refs/} | tr '/' '-')
          echo "GITHUB_HEAD = ${GITHUB_HEAD}"
          echo "::set-output name=head::${GITHUB_HEAD}"

          if $IS_CI_TEST; then
            echo "::set-output name=base::master"
          else
            GITHUB_BASE=${GITHUB_BASE#refs/heads/}
            GITHUB_BASE=$(echo ${GITHUB_BASE#refs/} | tr '/' '-')
            echo "GITHUB_BASE = ${GITHUB_BASE}"
            echo "::set-output name=base::${GITHUB_BASE}"
          fi

      - name: >
          Plan: compare ${{ steps.branch.outputs.head }} to ${{ steps.branch.outputs.base }}
        run: echo

      - name: Download base output
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          GITHUB_BASE: ${{ steps.branch.outputs.base }}
          GITHUB_HEAD: ${{ steps.branch.outputs.head }}
        run: |
          mkdir -p .snapshots/branches
          aws s3 cp s3://citeproc-rs-test-results/.snapshots/branches/$GITHUB_BASE .snapshots/branches/$GITHUB_BASE

      - name: Install Rust nightly-2021-05-18
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2021-05-18
            override: true
      - uses: Swatinem/rust-cache@v1

      - name: "Build tools package"
        run: cargo build --package tools
      - name: "Pull locales"
        run: cargo pull-locales
      - name: "Log test suite results"
        run: cargo test-suite store
      - name: "Compare test suite results for regressions"
        env:
          GITHUB_BASE: ${{ steps.branch.outputs.base }}
          GITHUB_HEAD: ${{ steps.branch.outputs.head }}
        run: |
          cp .snapshots/current .snapshots/branches/$GITHUB_HEAD
          cargo test-suite diff $GITHUB_BASE..$GITHUB_HEAD
      - name: "Upload test result artifacts"
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          GITHUB_HEAD: ${{ steps.branch.outputs.head }}
          GITHUB_BASE: ${{ steps.branch.outputs.base }}
        run: |
          if test -f .snapshots/current; then
            aws s3 cp .snapshots/current s3://citeproc-rs-test-results/.snapshots/branches/$GITHUB_HEAD
            aws s3 cp .snapshots/current s3://citeproc-rs-test-results/.snapshots/commits/$GITHUB_SHA
          fi

  wasm_tests:
    name: "Test the WASM package"
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust 1.52.1
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.52.1
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: cargo-debug-wasm

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        working-directory: crates/wasm/js-tests
        run: yarn install

      - name: Build WASM
        working-directory: crates/wasm/js-tests
        run: yarn build

      - name: Download Firefox ESR from zotero-standalone-build
        working-directory: crates/wasm/js-tests
        run: ./install_firefox.sh

      - name: Run tests, including in Firefox ESR
        working-directory: crates/wasm/js-tests
        run: MUST_RUN_FIREFOX_TESTS=1 yarn test

      # not necessary because we install @citeproc-rs/wasm without yarn knowing now
      # # otherwise, the yarn cache will contain a different @citeproc-rs/wasm
      # # entry every time.
      # - name: Clean yarn cache dir of wasm output
      #   run: |
      #     cd "$(yarn cache dir)"
      #     ls | grep citeproc-rs-wasm | xargs rm -rf

